-- ASTRAL STORE - TABLA DE PEDIDOS PARA SUPABASE
-- Ejecuta todo este archivo en Supabase > SQL Editor > New query.
--
-- El número de compra lo genera SUPABASE automáticamente:
-- 1000, 1001, 1002, 1003...
-- También guarda exactamente qué producto se pidió.

create table if not exists public.pedidos (
  id bigint generated always as identity primary key,
  numero_compra bigint generated by default as identity (start with 1000 increment by 1) unique not null,
  producto text not null,
  juego text not null,
  precio numeric(10,2) not null check (precio >= 0),
  id_free_fire text,
  fecha timestamptz not null default now(),
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'pagado', 'entregado', 'cancelado'))
);

-- Índices útiles
create index if not exists pedidos_numero_compra_idx
  on public.pedidos (numero_compra);

create index if not exists pedidos_fecha_idx
  on public.pedidos (fecha desc);

-- Función que crea el pedido y devuelve el número de compra.
-- Así el número NO lo genera el navegador: lo genera PostgreSQL/Supabase.
create or replace function public.crear_pedido(
  p_producto text,
  p_juego text,
  p_precio numeric,
  p_id_free_fire text default null
)
returns table (
  numero_compra bigint,
  producto text,
  juego text,
  precio numeric,
  id_free_fire text,
  fecha timestamptz,
  estado text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_producto is null or length(trim(p_producto)) = 0 then
    raise exception 'El producto es obligatorio';
  end if;

  if p_juego is null or length(trim(p_juego)) = 0 then
    raise exception 'El juego es obligatorio';
  end if;

  if p_precio is null or p_precio < 0 then
    raise exception 'El precio no es válido';
  end if;

  return query
  insert into public.pedidos (
    producto,
    juego,
    precio,
    id_free_fire
  )
  values (
    trim(p_producto),
    trim(p_juego),
    p_precio,
    nullif(trim(coalesce(p_id_free_fire, '')), '')
  )
  returning
    pedidos.numero_compra,
    pedidos.producto,
    pedidos.juego,
    pedidos.precio,
    pedidos.id_free_fire,
    pedidos.fecha,
    pedidos.estado;
end;
$$;

-- Permite que la página de Astral Store pueda llamar a la función.
grant execute on function public.crear_pedido(text, text, numeric, text)
  to anon, authenticated;

-- Seguridad: no se permite modificar directamente la tabla desde el navegador.
alter table public.pedidos enable row level security;

-- No creamos políticas de INSERT/UPDATE/DELETE.
-- La página utilizará únicamente crear_pedido().
--
-- En Supabase, después de hacer una compra, verás:
--
-- numero_compra | producto              | juego    | precio | fecha | estado
-- 1000          | 1100 Diamantes        | freefire |  5.00  | ...   | pendiente
-- 1001          | 500 Robux             | roblox   |  6.00  | ...   | pendiente
--
-- IMPORTANTE:
-- El archivo NO contiene claves de Supabase.
-- Las claves deben colocarse después en el JavaScript de la página.
